# Generated by Django 2.1.2 on 2018-11-07 02:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role_type', models.IntegerField(default=0, verbose_name='角色类型')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('is_id_verified', models.BooleanField(default=False, verbose_name='身份是否验证')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('label', models.CharField(max_length=80, verbose_name='标签')),
                ('bsb', models.CharField(max_length=80)),
                ('account_number', models.CharField(max_length=80)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=80)),
                ('swift', models.CharField(max_length=100)),
                ('beneficiary_address', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountbank', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('role_name', models.CharField(max_length=50)),
                ('role_description', models.CharField(max_length=100)),
                ('authority', models.CharField(max_length=100)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminrole', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('operate_id', models.IntegerField()),
                ('operate_email', models.CharField(max_length=80)),
                ('type', models.IntegerField()),
                ('actions', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('amount', models.BigIntegerField()),
                ('actual_amount', models.BigIntegerField(default=0)),
                ('bank_txid', models.CharField(max_length=80)),
                ('blcokchain_txid', models.CharField(max_length=80)),
                ('issue_txid', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('order', models.CharField(max_length=16)),
                ('status', models.IntegerField(default=0)),
                ('currency', models.CharField(default='AUD', max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Eth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('eth_label', models.CharField(max_length=80, null=True)),
                ('eth_address', models.CharField(max_length=80, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('amount', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('operate', models.IntegerField()),
                ('is_sms_active', models.BooleanField(default=False)),
                ('is_mail_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('phone', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('KYC_status', models.IntegerField(default=2)),
                ('KYC_reason', models.CharField(max_length=80)),
                ('avatar', models.TextField(default=None, null=True)),
                ('is_binding_google', models.BooleanField(default=False)),
                ('is_binding_sms', models.BooleanField(default=False)),
                ('google_secret_key', models.CharField(max_length=80)),
                ('current_amount', models.BigIntegerField()),
                ('frozen', models.BigIntegerField()),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserKyc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('given_name', models.CharField(max_length=80)),
                ('family_name', models.CharField(max_length=80)),
                ('birthday', models.DateTimeField()),
                ('kyc_file_type', models.CharField(max_length=80)),
                ('id_document_type', models.CharField(max_length=80)),
                ('file_number', models.CharField(max_length=80)),
                ('expire_date', models.DateTimeField()),
                ('kyc_file', models.TextField()),
                ('document_file', models.TextField()),
                ('country', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('zip_code', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userkyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='删除时间')),
                ('amount', models.BigIntegerField()),
                ('actual_amount', models.BigIntegerField(default=0)),
                ('bank_txid', models.CharField(max_length=80)),
                ('blcokchain_txid', models.CharField(max_length=80)),
                ('redeem_txid', models.CharField(max_length=80)),
                ('status', models.IntegerField(default=0)),
                ('currency', models.CharField(default='AUD', max_length=80)),
                ('bank_label', models.CharField(max_length=80)),
                ('bank_bsb', models.CharField(max_length=80)),
                ('bank_account_number', models.CharField(max_length=80)),
                ('bank_bank_name', models.CharField(max_length=100)),
                ('bank_account_name', models.CharField(max_length=80)),
                ('bank_swift', models.CharField(max_length=100)),
                ('bank_beneficiary_address', models.CharField(max_length=255)),
                ('bank_address', models.CharField(max_length=255)),
                ('remark', models.TextField()),
                ('address', models.CharField(max_length=80)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AddField(
            model_name='fee',
            name='withdraw_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='app.Withdraw'),
        ),
        migrations.AddField(
            model_name='eth',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit', to='app.Profile'),
        ),
    ]
