# Generated by Django 2.1.2 on 2018-11-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='frozen',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
