# Generated by Django 2.1.2 on 2018-11-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181115_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkyc',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='expire_date',
            field=models.DateTimeField(null=True),
        ),
    ]
